### ISSUE TITLE
Update for rstan 2.17.2 and StanHeaders 2.17.1

### ISSUE THREAD

**Issue by yizhang-cae** [metrumresearchgroup/TorstenHeaders#1]
In order to use Torsten 2.17.1 (updated to stan & stan_math 2.17.1) we need also update this installation script. The updated version should grab new rstan and StanHeaders and replace stan & math libraries with metrum's version.

**Comment by yonicd** [comment]
merged PR https://github.com/metrumresearchgroup/TorstenHeaders/commit/daa2b7f4d16a325593edf7dd841de50edbb724f3
