### ISSUE TITLE
Change to rstan_version = 2.18.2

### ISSUE THREAD

**Issue by billgillespie** [metrumresearchgroup/TorstenHeaders#3]
The current version of TorstenHeaders installs RStan version 2.18.1 by default. There is a bug in RStan version 2.18.1 that causes read_stan_csv to fail. See https://github.com/stan-dev/rstan/issues/578. 

This was fixed in RStan version 2.18.2. When Torsten is installed using install_torsten(rstan_version = "2.18.2"), read_stan_csv runs successfully on csv files generated by Torsten examples in https://github.com/metrumresearchgroup/example-models using CmdStan.

I propose changing the default RStan version for Torsten to 2.18.2.

**Comment by yizhang-cae** [comment]
Also re-ship the container repo https://github.com/metrumresearchgroup/Torsten

**Comment by yizhang-cae** [comment]
This is in. Closing.
